name: Publish to Docker Registry
on:
  # release:
  #     types: [published]
  #push:
    #branches:
    #  - main    
  #schedule:
   # - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
  # workflow_run:
  #   workflows: ["SLSA Go releaser"]
  #   types:
  #     - completed
  workflow_dispatch:
  
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - name: Publish to Docker Registry      
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: senexcrenshaw/xteve
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: ${{ github.event_name != 'schedule' }}
          tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
          default_branch: main
